In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

#2. Print the NUMPY version and the configuration.







In [2]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a1 = np.random.random((2,3,5))
import numpy.random
from numpy.random import random as a3
a3 = ((2,3,5))

#4. Print a.
print(a1)
print(np.random.random((2,3,5)))
print(a3)

[[[0.99376272 0.26792238 0.34635105 0.55443075 0.2184253 ]
  [0.36216664 0.03016691 0.79672666 0.29301652 0.43479707]
  [0.6575301  0.72322372 0.34209976 0.55826496 0.20599492]]

 [[0.32989821 0.64355617 0.46679742 0.23190266 0.07817957]
  [0.58665367 0.86829743 0.62431903 0.62379305 0.13295477]
  [0.78520883 0.28606445 0.35336161 0.88346483 0.85161226]]]
[[[0.24279382 0.03742294 0.48880407 0.37127933 0.23617877]
  [0.1420119  0.17204656 0.63061111 0.15399373 0.39119617]
  [0.21094883 0.73955983 0.77475288 0.88486528 0.97303471]]

 [[0.11340554 0.18072959 0.96694293 0.25907483 0.35064684]
  [0.96638575 0.0302519  0.70752938 0.97704572 0.69495098]
  [0.57296624 0.00815449 0.88264167 0.72953926 0.04849624]]]
(2, 3, 5)


In [3]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

import numpy as np

b = np.ones((5,2,3))

#6. Print b.

print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [4]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a1.size == b.size)




True


In [5]:
#8. Are you able to add a and b? Why or why not?
#NO BECAUSE THEY DO NOT HAVE THE SAME SIZE


In [6]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.transpose(1,2,0)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [21]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a1 + c
print(d)
d.size


[[[1.99376272 1.26792238 1.34635105 1.55443075 1.2184253 ]
  [1.36216664 1.03016691 1.79672666 1.29301652 1.43479707]
  [1.6575301  1.72322372 1.34209976 1.55826496 1.20599492]]

 [[1.32989821 1.64355617 1.46679742 1.23190266 1.07817957]
  [1.58665367 1.86829743 1.62431903 1.62379305 1.13295477]
  [1.78520883 1.28606445 1.35336161 1.88346483 1.85161226]]]


30

In [8]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(d)
#NOW IT WORKS BECAUSE BOTH ARRAYS HAVE THE SAME SIZE


[[[1.99376272 1.26792238 1.34635105 1.55443075 1.2184253 ]
  [1.36216664 1.03016691 1.79672666 1.29301652 1.43479707]
  [1.6575301  1.72322372 1.34209976 1.55826496 1.20599492]]

 [[1.32989821 1.64355617 1.46679742 1.23190266 1.07817957]
  [1.58665367 1.86829743 1.62431903 1.62379305 1.13295477]
  [1.78520883 1.28606445 1.35336161 1.88346483 1.85161226]]]


In [9]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a1,c)

print(e)

print(e==a1)

[[[0.99376272 0.26792238 0.34635105 0.55443075 0.2184253 ]
  [0.36216664 0.03016691 0.79672666 0.29301652 0.43479707]
  [0.6575301  0.72322372 0.34209976 0.55826496 0.20599492]]

 [[0.32989821 0.64355617 0.46679742 0.23190266 0.07817957]
  [0.58665367 0.86829743 0.62431903 0.62379305 0.13295477]
  [0.78520883 0.28606445 0.35336161 0.88346483 0.85161226]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [10]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.amax(d)
print(d_max)
d_min=np.amin(d)
print(d_min)
d_mean=np.mean(d)
print(d_mean)

1.993762721154341
1.0301669066902688
1.484364779784467


In [19]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
print(f)

[[[0.99376272 0.26792238 0.34635105 0.55443075 0.2184253 ]
  [0.36216664 0.03016691 0.79672666 0.29301652 0.43479707]
  [0.6575301  0.72322372 0.34209976 0.55826496 0.20599492]]

 [[0.32989821 0.64355617 0.46679742 0.23190266 0.07817957]
  [0.58665367 0.86829743 0.62431903 0.62379305 0.13295477]
  [0.78520883 0.28606445 0.35336161 0.88346483 0.85161226]]]


30

In [33]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
    #d_mean> value > d_min --> 25
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
    #d_max> value > d_mean --> 75
#If a value equals to d_mean, assign 50 to the corresponding value in f.
    #value = d_mean --> 50
#Assign 0 to the corresponding value(s) in f for d_min in d.
#value = d_min --> 0
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

list_d = [x for y in d for v in y for x in v]
list_f = []
for n in list_d:
    if n==d_mean:
        list_f.append(50)
    elif n==d_max:
        list_f.append(100)
    elif d_max> n > d_mean:
        list_f.append(75)
    elif d_mean> n > d_min:
        list_f.append(25)
    elif n==d_min:
        list_f.append(0)
f = np.array(list_f).reshape(2,3,5)

print(f)



"""
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

[[[100  25  25  75  25]
  [ 25   0  75  25  25]
  [ 75  75  25  75  25]]

 [[ 25  75  25  25  25]
  [ 75  75  75  75  25]
  [ 75  25  25  75  75]]]


'\n#17. Print d and f. Do you have your expected f?\n#For instance, if your d is:\n#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],\n        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],\n        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],\n\n       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],\n        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],\n        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])\n\n#Your f should be:\n#array([[[ 75.,  75.,  75.,  25.,  75.],\n        [ 75.,  75.,  25.,  25.,  25.],\n        [ 75.,  25.,  75.,  75.,  75.]],\n\n       [[ 25.,  25.,  25.,  25., 100.],\n        [ 75.,  75.,  75.,  75.,  75.],\n        [ 25.,  75.,   0.,  75.,  75.]]])\n'

In [37]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
#        [ 'D',  'D',  'B',  'B',  'B'],
#        [ 'D',  'B',  'D',  'D',  'D']],
#
#       [[ 'B',  'B',  'B',  'B',  'E'],
#        [ 'D',  'D',  'D',  'D',  'D'],
#        [ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.


list_d = [h for i in d for j in i for h in j]

list_f2 = []
for r in list_d:
    if r==d_mean:
        list_f2.append("A")
    elif r==d_max:
        list_f2.append("B")
    elif d_max> r > d_mean:
        list_f2.append("C")
    elif d_mean> r > d_min:
        list_f2.append("D")
    elif r==d_min:
        list_f2.append("E")
f2 = np.array(list_f2).reshape(2,3,5)

print(f2)


[[['B' 'D' 'D' 'C' 'D']
  ['D' 'E' 'C' 'D' 'D']
  ['C' 'C' 'D' 'C' 'D']]

 [['D' 'C' 'D' 'D' 'D']
  ['C' 'C' 'C' 'C' 'D']
  ['C' 'D' 'D' 'C' 'C']]]
