In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

#2. Print the NUMPY version and the configuration.







In [2]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a1 = np.random.random((2,3,5))
import numpy.random
from numpy.random import random as a3
a3 = ((2,3,5))

#4. Print a.
print(a1)
print(np.random.random((2,3,5)))
print(a3)

[[[0.14810714 0.94258184 0.67028779 0.47299064 0.12906809]
  [0.49611799 0.36422163 0.3245805  0.38364258 0.26474526]
  [0.80150948 0.46169048 0.48022891 0.56064671 0.90077407]]

 [[0.50400761 0.27554222 0.78008381 0.74011475 0.12485991]
  [0.40342199 0.06245528 0.03121458 0.42658485 0.40811178]
  [0.60393067 0.59534158 0.10551899 0.14433371 0.23029629]]]
[[[0.67113604 0.76936481 0.9207662  0.53050333 0.62101008]
  [0.33169142 0.50052958 0.59229638 0.89681538 0.10148835]
  [0.8428519  0.14834014 0.89466693 0.30951461 0.04993403]]

 [[0.32276198 0.65625661 0.55600097 0.94987401 0.53024401]
  [0.55026203 0.60831587 0.0425585  0.91558997 0.39634507]
  [0.69682456 0.28867617 0.07840467 0.3233498  0.5284356 ]]]
(2, 3, 5)


In [3]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

import numpy as np

b = np.ones((5,2,3))

#6. Print b.

print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [4]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a1.size == b.size)




True


In [5]:
#8. Are you able to add a and b? Why or why not?
#NO BECAUSE THEY DO NOT HAVE THE SAME SIZE


In [6]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.transpose(1,2,0)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [7]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a1 + c
print(d)


[[[1.14810714 1.94258184 1.67028779 1.47299064 1.12906809]
  [1.49611799 1.36422163 1.3245805  1.38364258 1.26474526]
  [1.80150948 1.46169048 1.48022891 1.56064671 1.90077407]]

 [[1.50400761 1.27554222 1.78008381 1.74011475 1.12485991]
  [1.40342199 1.06245528 1.03121458 1.42658485 1.40811178]
  [1.60393067 1.59534158 1.10551899 1.14433371 1.23029629]]]


In [8]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(d)
#NOW IT WORKS BECAUSE BOTH ARRAYS HAVE THE SAME SIZE


[[[1.14810714 1.94258184 1.67028779 1.47299064 1.12906809]
  [1.49611799 1.36422163 1.3245805  1.38364258 1.26474526]
  [1.80150948 1.46169048 1.48022891 1.56064671 1.90077407]]

 [[1.50400761 1.27554222 1.78008381 1.74011475 1.12485991]
  [1.40342199 1.06245528 1.03121458 1.42658485 1.40811178]
  [1.60393067 1.59534158 1.10551899 1.14433371 1.23029629]]]


In [9]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a1,c)

print(e)

print(e==a1)

[[[0.14810714 0.94258184 0.67028779 0.47299064 0.12906809]
  [0.49611799 0.36422163 0.3245805  0.38364258 0.26474526]
  [0.80150948 0.46169048 0.48022891 0.56064671 0.90077407]]

 [[0.50400761 0.27554222 0.78008381 0.74011475 0.12485991]
  [0.40342199 0.06245528 0.03121458 0.42658485 0.40811178]
  [0.60393067 0.59534158 0.10551899 0.14433371 0.23029629]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [12]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.amax(d)
print(d_max)
d_min=np.amin(d)
print(d_min)
d_mean=np.mean(d)
print(d_mean)

1.9425818392144016
1.0312145773949777
1.4279003710231415


In [15]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
print(f)

[[[0.14810714 0.94258184 0.67028779 0.47299064 0.12906809]
  [0.49611799 0.36422163 0.3245805  0.38364258 0.26474526]
  [0.80150948 0.46169048 0.48022891 0.56064671 0.90077407]]

 [[0.50400761 0.27554222 0.78008381 0.74011475 0.12485991]
  [0.40342199 0.06245528 0.03121458 0.42658485 0.40811178]
  [0.60393067 0.59534158 0.10551899 0.14433371 0.23029629]]]


In [ ]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
    #d_mean> value > d_min --> 25
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
    #d_max> value > d_mean --> 75
#If a value equals to d_mean, assign 50 to the corresponding value in f.
    #value = d_mean --> 50
#Assign 0 to the corresponding value(s) in f for d_min in d.
#value = d_mean --> 50
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
"""




"""
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""