In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

#2. Print the NUMPY version and the configuration.







In [2]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a1 = np.random.random((2,3,5))
import numpy.random
from numpy.random import random as a3
a3 = ((2,3,5))

#4. Print a.
print(a1)
print(np.random.random((2,3,5)))
print(a3)

[[[0.48198405 0.55196844 0.04033729 0.64714882 0.02996618]
  [0.39638389 0.08476308 0.69778431 0.10682555 0.96084056]
  [0.25180474 0.01528995 0.57094537 0.10085053 0.08390111]]

 [[0.76393422 0.69638817 0.43354312 0.24860787 0.06969219]
  [0.6398287  0.8320598  0.06162665 0.95053102 0.52781835]
  [0.14293486 0.17167829 0.51131012 0.20203212 0.02300305]]]
[[[4.62710373e-01 4.86230292e-01 8.36307914e-01 3.73611733e-01
   1.36339637e-01]
  [3.14823970e-01 8.54416184e-01 1.68089410e-01 8.77699762e-01
   3.98609312e-02]
  [6.02294213e-01 1.59706037e-01 9.69275970e-01 4.44218885e-01
   6.66578891e-01]]

 [[5.13787244e-01 5.90676480e-01 3.85685430e-01 4.29503906e-01
   1.40894854e-01]
  [7.27594748e-01 5.70342048e-04 1.90177456e-01 4.02269950e-01
   1.41835088e-01]
  [2.15385368e-02 5.41719235e-02 2.17345985e-01 4.88686919e-01
   9.38668550e-01]]]
(2, 3, 5)


In [3]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

import numpy as np

b = np.ones((5,2,3))

#6. Print b.

print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [4]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a1.size == b.size)




True


In [5]:
#8. Are you able to add a and b? Why or why not?
#NO BECAUSE THEY DO NOT HAVE THE SAME SIZE


In [6]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.transpose(1,2,0)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [7]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a1 + c
print(d)


[[[1.48198405 1.55196844 1.04033729 1.64714882 1.02996618]
  [1.39638389 1.08476308 1.69778431 1.10682555 1.96084056]
  [1.25180474 1.01528995 1.57094537 1.10085053 1.08390111]]

 [[1.76393422 1.69638817 1.43354312 1.24860787 1.06969219]
  [1.6398287  1.8320598  1.06162665 1.95053102 1.52781835]
  [1.14293486 1.17167829 1.51131012 1.20203212 1.02300305]]]


In [8]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(d)
#NOW IT WORKS BECAUSE BOTH ARRAYS HAVE THE SAME SIZE


[[[1.48198405 1.55196844 1.04033729 1.64714882 1.02996618]
  [1.39638389 1.08476308 1.69778431 1.10682555 1.96084056]
  [1.25180474 1.01528995 1.57094537 1.10085053 1.08390111]]

 [[1.76393422 1.69638817 1.43354312 1.24860787 1.06969219]
  [1.6398287  1.8320598  1.06162665 1.95053102 1.52781835]
  [1.14293486 1.17167829 1.51131012 1.20203212 1.02300305]]]


In [9]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a1,c)

print(e)

print(e==a1)

[[[0.48198405 0.55196844 0.04033729 0.64714882 0.02996618]
  [0.39638389 0.08476308 0.69778431 0.10682555 0.96084056]
  [0.25180474 0.01528995 0.57094537 0.10085053 0.08390111]]

 [[0.76393422 0.69638817 0.43354312 0.24860787 0.06969219]
  [0.6398287  0.8320598  0.06162665 0.95053102 0.52781835]
  [0.14293486 0.17167829 0.51131012 0.20203212 0.02300305]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [10]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.amax(d)
print(d_max)
d_min=np.amin(d)
print(d_min)
d_mean=np.mean(d)
print(d_mean)

1.960840564681535
1.0152899544665228
1.3765260806469262


In [11]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
print(f)

[[[0.48198405 0.55196844 0.04033729 0.64714882 0.02996618]
  [0.39638389 0.08476308 0.69778431 0.10682555 0.96084056]
  [0.25180474 0.01528995 0.57094537 0.10085053 0.08390111]]

 [[0.76393422 0.69638817 0.43354312 0.24860787 0.06969219]
  [0.6398287  0.8320598  0.06162665 0.95053102 0.52781835]
  [0.14293486 0.17167829 0.51131012 0.20203212 0.02300305]]]


In [31]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
    #d_mean> value > d_min --> 25
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
    #d_max> value > d_mean --> 75
#If a value equals to d_mean, assign 50 to the corresponding value in f.
    #value = d_mean --> 50
#Assign 0 to the corresponding value(s) in f for d_min in d.
#value = d_min --> 0
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

for x in f_array:
    if x==d_mean:
        f_array.append(0)
    else x==d_max:
        f_array.apped(100)
    else d_max> x > d_mean:
        f_array.append(75)
    else d_mean> x > d_min:
        f_array.append(25)
print(f_array)
                
    


"""
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

SyntaxError: invalid syntax (<ipython-input-31-4ef97109d06e>, line 16)